version: '3'

services:
  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofrontend

  todofront:
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todobackend
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - 3000:3000

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    platform: linux/amd64
